apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd-deployment
        image: ashok0709/app:1.0
        env:
        - name: MYSQL_HOST
          value: db-deployment
        - name: MYSQL_PORT
          value: "3306"
        ports:
        - containerPort: 80
