name: Deploy a sample Application to AKS
 
on:
  workflow_dispatch:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build and push images
      run: |
        docker build -t ashok0709/app:1.0 -f dockerfile-app .
        docker build -t ashok0709/db:1.0 -f dockerfile-db .
        docker push ashok0709/app:1.0
        docker push ashok0709/db:1.0
        
    - name: Login and Deploy to AKS
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az login
          az account set --subscription ${{ vars.AKS_SUBSCRIPTION_ID }}
          az aks get-credentials --resource-group rg-deployment-centralindia-01 --name aks-deployment-centralindia-01
          az aks install-cli
          kubectl version --client
          kubectl apply -f app-deployment.yml
          kubectl apply -f app-svc.yml
          kubectl apply -f db-deployment.yml
          kubectl apply -f db-svc.yml


    - name: run blue-green deployment
      run: |
        # make changes in the application to create a new feature and then build a new image
        docker build -t ashok0709/app:2.0 -f dockerfile-app .
        docker build -t ashok0709/db:2.0 -f dockerfile-db .
        docker push ashok0709/app:2.0
        docker push ashok0709/db:2.0   
        sed -i 's/app:1.0/app:2.0/g' app-deployment.yml
        sed -i 's/db:1.0/db:2.0/g' db-deployment.yml
        kubectl apply -f app-deployment.yml
        kubectl apply -f db-deployment.yml                             
